apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: netflix
spec:
  selector:
    matchLabels:
      app: netflix
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - name: netflix
          image: kundankumar344/netflix:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000 # The port that the container is running on in the cluster
          env:
          - name: TMDB_V3_API_KEY
            valueFrom:
              secretKeyRef:
                name: tmdb-api-key
                key: TMDB_V3_API_KEY


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: zomato-svc
spec:
  selector:
    app: zomato
  ports:
    - protocol: "TCP"
      port: 3000 # The port that the service is running on in the cluster
      targetPort: 3000 # The port exposed by the service
  type: LoadBalancer # type of the service.